language: java
jdk:
- oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
    secure: 1WBkiDJWE7tYET/WZ/nV2RxD0C4l5xmOLzwO/+xnA+rlxpWkAfD8/ZKOv3NhSLaNu7zLSvLg2w59qBoCfFlpKNslDGLsZDduKGG6Bo0EjPgcIDdnO73XADm8fOq0ITXbUAWBGuXs2TWBzczigobzm+Pam+rWKgCAx7W50iE9c62+fFV4T6Qx2/AnOtqOjLkgPG3kou4jIAKGq6jR5wELOmr9kkvZp2mPzWtzpSEEwRWPAaQ1K6LSBNRX1uYgXftxznCErNpgNPmVXV64zrO6sdqc4j/msrmLu1565eJMmK6+dSBztdkucGhUukrd39Mc8z4YDFxt8x1Hlgjnvrn5/594ewhnPMzVeZWEW3BgFY7XXljZAhqcAZnk3RhTJE0voJ4EM+hPMjJnrarkGOMLutWIfLQZm7zVXEwZEOK4hBdltBdUnaYPOU8jHdqV/T6tPns6Hwtv32YxecrTyWe3BhddY0ECCls7T0P5NeE0TDCOP7h2CLqWXcAJ3x50rDy9C9JSc/rKUGIO7xA3HH2XzvVhhn/qoQsM8D9GGB8D/41v7RHXzE+0x3PauXIc+6UCTfMC4w7yKmPVyZOHYM7WuJqAQU4LzN8BF5fihpsKdG63u0/UuYpzQ5Rcp1YJ8N0Y5u40swJGl+KeGVS8ZiRsHznJZcql301FnmshFCri1jU=
script: "./gradlew clean :blog:jbake :blog:publishGhPages"
branches:
  only:
  - master
